exclude_globs = ["src/main.rs", "tests/support/echo_server.rs", "tests/support/multi_echo_server.rs"]
cap_lints = true
test_tool = "nextest"
profile = "mutants"
timeout_multiplier = 1.0
build_timeout_multiplier = 2.0
